providers = ["node"]

[phases.install]
cmds = [
  "npm install -g corepack", 
  "corepack enable", 
  "corepack prepare pnpm@9.1.0 --activate",
  "pnpm install"
]

[phases.build]
cmds = [
  "pnpm run generate", # Generate Prisma types
  "pnpm run build" # Build the project
]

[start]
cmd = "pnpm run start"